# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6002b4deb7bae345b03a9b2ee0d66a822116867f7e5cc1826a4bfdbbe7b917095b79fbd965c0f5e0fe779cd2935fea111a10bf95fc230eec33cbeca7e813017b

test:
  secret_key_base: a6ab33e17bae248d5c4b993d1341fbf2852b5e0ef12f1a7bcb3d85b6dca3fb95191877fcf05047f657b7ffeba0ca155c18832958c076a466b1d2985453c3fb59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
